### ISSUE TITLE
Detailed test output seems to be missing

### ISSUE THREAD

**Issue by Nicolapps** [skills17/karma-helpers#2]
When some tests are run using `npm run test`, I only get the end summary of the points, and not the details (e.g. why did some test fail). Here is what I have:

```
$ npm run test

> skills17-bugreport@1.0.0 test {project path}
> karma start


------------       RESULT       ------------

Summary:
  Sample group 1: 1/1 point
    ✔ Group1 > should work: ok
  Sample group 2: 0/1 point
    ✖ Group2 > should also work: failed

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skills17-bugreport@1.0.0 test: `karma start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skills17-bugreport@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/...
```

Is there something that I need to enable in order to have the full output?

You can see how I tried to set up the environment on the private repo.

**Comment by Nicolapps** [comment]
I just saw that the footer message talking about the detailed output is [explicitly disabled](https://github.com/skills17/karma-helpers/blob/eb0b2532b6f1837750cf2f5b105c7890fa21c132/src/reporter.ts#L41) in `Reporter`. So is it just that `karma-helpers` doesn’t support showing the detailed output, and competitors should always use the HTML file?

In that case, the header image in the [README file](https://github.com/skills17/karma-helpers#skills17karma-helpers) should probably not have the footer line.

**Comment by cyrilwanner** [comment]
Yes, the detailed output is currently not implemented as the goal was to provide an initial version for the automated run only and competitors should use the HTML file. So that's why the footer message is disabled until it gets implemented.
But I should have time to look at this again on the weekend, it shouldn't actually be too complicated to implement I think.

(and yes, the image from the readme was copied from another package out of laziness ;) but it should be correct again once the feature has been added)

**Comment by cyrilwanner** [comment]
This feature has now been added in `v1.1.0` and is enabled by default for the non-json reporter, meaning the same `mocha` messages that would be visible in the browser are now also logged in the terminal. Additionally, the browser console is now forwarded to the terminal, so `console.log` statements etc are now also visible.
![image](https://user-images.githubusercontent.com/2709252/106388054-0653a780-63dd-11eb-86d6-bc62e17fe830.png)
